//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 09:58:37 AM CET 
//


package tmp;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;



@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "generalInfo",
    "sndr"
})
@XmlRootElement(name = "mXmlDetailsS")
public class MXmlDetailsS {

    @XmlElement(name = "GeneralInfo", required = true)
    protected MXmlDetailsS.GeneralInfo generalInfo;
    @XmlElement(name = "Sndr", required = true)
    protected MXmlDetailsS.Sndr sndr;

    public MXmlDetailsS.GeneralInfo getGeneralInfo() {
        return generalInfo;
    }

    public void setGeneralInfo(MXmlDetailsS.GeneralInfo value) {
        this.generalInfo = value;
    }

    public MXmlDetailsS.Sndr getSndr() {
        return sndr;
    }

    public void setSndr(MXmlDetailsS.Sndr value) {
        this.sndr = value;
    }

	@XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "dealType",
        "c20",
        "status",
        "dealStsDate",
        "dealStsTime",
        "uti",
        "usi"
    })
    public static class GeneralInfo {

        @XmlElement(name = "DealType")
        protected short dealType;
        @XmlElement(name = "C20")
        protected int c20;
        @XmlElement(name = "Status", required = true)
        protected String status;
        @XmlElement(name = "DealStsDate")
        protected int dealStsDate;
        @XmlElement(name = "DealStsTime")
        protected int dealStsTime;
        @XmlElement(name = "UTI", required = true)
        protected String uti;
        @XmlElement(name = "USI", required = true)
        protected String usi;

        public short getDealType() {
            return dealType;
        }

        public void setDealType(short value) {
            this.dealType = value;
        }

        public int getC20() {
            return c20;
        }

        public void setC20(int value) {
            this.c20 = value;
        }

        public String getStatus() {
            return status;
        }

        public void setStatus(String value) {
            this.status = value;
        }

        public int getDealStsDate() {
            return dealStsDate;
        }

        public void setDealStsDate(int value) {
            this.dealStsDate = value;
        }

        public int getDealStsTime() {
            return dealStsTime;
        }

        public void setDealStsTime(int value) {
            this.dealStsTime = value;
        }

        public String getUTI() {
            return uti;
        }

        public void setUTI(String value) {
            this.uti = value;
        }

        public String getUSI() {
            return usi;
        }

        public void setUSI(String value) {
            this.usi = value;
        }

    }


    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "cptyBIC",
        "senderBIC",
        "fsn",
        "frc",
        "seqA",
        "seqB",
        "seqB1",
        "seqB2",
        "seqC",
        "seqD",
        "seqE"
    })
    public static class Sndr {

        @XmlElement(name = "CptyBIC", required = true)
        protected String cptyBIC;
        @XmlElement(name = "SenderBIC", required = true)
        protected String senderBIC;
        @XmlElement(name = "FSN", required = true)
        protected String fsn;
        @XmlElement(name = "FRC", required = true)
        protected String frc;
        @XmlElement(name = "SeqA", required = true)
        protected MXmlDetailsS.Sndr.SeqA seqA;
        @XmlElement(name = "SeqB", required = true)
        protected MXmlDetailsS.Sndr.SeqB seqB;
        @XmlElement(name = "SeqB1", required = true)
        protected MXmlDetailsS.Sndr.SeqB1 seqB1;
        @XmlElement(name = "SeqB2", required = true)
        protected MXmlDetailsS.Sndr.SeqB2 seqB2;
        @XmlElement(name = "SeqC", required = true)
        protected MXmlDetailsS.Sndr.SeqC seqC;
        @XmlElement(name = "SeqD", required = true)
        protected String seqD;
        @XmlElement(name = "SeqE", required = true)
        protected MXmlDetailsS.Sndr.SeqE seqE;

        public String getCptyBIC() {
            return cptyBIC;
        }

        public void setCptyBIC(String value) {
            this.cptyBIC = value;
        }

        public String getSenderBIC() {
            return senderBIC;
        }

        public void setSenderBIC(String value) {
            this.senderBIC = value;
        }

        public String getFSN() {
            return fsn;
        }

        public void setFSN(String value) {
            this.fsn = value;
        }

        public String getFRC() {
            return frc;
        }

        public void setFRC(String value) {
            this.frc = value;
        }

        public MXmlDetailsS.Sndr.SeqA getSeqA() {
            return seqA;
        }

        public void setSeqA(MXmlDetailsS.Sndr.SeqA value) {
            this.seqA = value;
        }

        public MXmlDetailsS.Sndr.SeqB getSeqB() {
            return seqB;
        }

        public void setSeqB(MXmlDetailsS.Sndr.SeqB value) {
            this.seqB = value;
        }

        public MXmlDetailsS.Sndr.SeqB1 getSeqB1() {
            return seqB1;
        }

        public void setSeqB1(MXmlDetailsS.Sndr.SeqB1 value) {
            this.seqB1 = value;
        }

        public MXmlDetailsS.Sndr.SeqB2 getSeqB2() {
            return seqB2;
        }

        public void setSeqB2(MXmlDetailsS.Sndr.SeqB2 value) {
            this.seqB2 = value;
        }

        public MXmlDetailsS.Sndr.SeqC getSeqC() {
            return seqC;
        }

        public void setSeqC(MXmlDetailsS.Sndr.SeqC value) {
            this.seqC = value;
        }

        public String getSeqD() {
            return seqD;
        }

        public void setSeqD(String value) {
            this.seqD = value;
        }

        public MXmlDetailsS.Sndr.SeqE getSeqE() {
            return seqE;
        }

        public void setSeqE(MXmlDetailsS.Sndr.SeqE value) {
            this.seqE = value;
        }


        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f15A",
            "f20",
            "f21",
            "f22A",
            "f94A",
            "f22C",
            "f17T",
            "f17U",
            "f82A",
            "f87A",
            "f77D"
        })
        public static class SeqA {

            @XmlElement(name = "F15A", required = true)
            protected String f15A;
            @XmlElement(name = "F20")
            protected int f20;
            @XmlElement(name = "F21", required = true)
            protected String f21;
            @XmlElement(name = "F22A", required = true)
            protected String f22A;
            @XmlElement(name = "F94A", required = true)
            protected String f94A;
            @XmlElement(name = "F22C", required = true)
            protected String f22C;
            @XmlElement(name = "F17T", required = true)
            protected String f17T;
            @XmlElement(name = "F17U", required = true)
            protected String f17U;
            @XmlElement(name = "F82A", required = true)
            protected String f82A;
            @XmlElement(name = "F87A", required = true)
            protected String f87A;
            @XmlElement(name = "F77D", required = true)
            protected String f77D;

            public String getF15A() {
                return f15A;
            }

            public void setF15A(String value) {
                this.f15A = value;
            }

            public int getF20() {
                return f20;
            }

            public void setF20(int value) {
                this.f20 = value;
            }

            public String getF21() {
                return f21;
            }

            public void setF21(String value) {
                this.f21 = value;
            }

            public String getF22A() {
                return f22A;
            }

            public void setF22A(String value) {
                this.f22A = value;
            }

            public String getF94A() {
                return f94A;
            }

            public void setF94A(String value) {
                this.f94A = value;
            }

            public String getF22C() {
                return f22C;
            }

            /**
             * Sets the value of the f22C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF22C(String value) {
                this.f22C = value;
            }

            /**
             * Gets the value of the f17T property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF17T() {
                return f17T;
            }

            /**
             * Sets the value of the f17T property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF17T(String value) {
                this.f17T = value;
            }

            /**
             * Gets the value of the f17U property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF17U() {
                return f17U;
            }

            /**
             * Sets the value of the f17U property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF17U(String value) {
                this.f17U = value;
            }

            /**
             * Gets the value of the f82A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF82A() {
                return f82A;
            }

            /**
             * Sets the value of the f82A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF82A(String value) {
                this.f82A = value;
            }

            /**
             * Gets the value of the f87A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF87A() {
                return f87A;
            }

            /**
             * Sets the value of the f87A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF87A(String value) {
                this.f87A = value;
            }

            /**
             * Gets the value of the f77D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF77D() {
                return f77D;
            }

            /**
             * Sets the value of the f77D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF77D(String value) {
                this.f77D = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="F15B" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="F30T" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="F30V" type="{http://www.w3.org/2001/XMLSchema}int"/>
         *         &lt;element name="F36" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f15B",
            "f30T",
            "f30V",
            "f36"
        })
        public static class SeqB {

            @XmlElement(name = "F15B", required = true)
            protected String f15B;
            @XmlElement(name = "F30T")
            protected int f30T;
            @XmlElement(name = "F30V")
            protected int f30V;
            @XmlElement(name = "F36", required = true)
            protected String f36;

            /**
             * Gets the value of the f15B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF15B() {
                return f15B;
            }

            /**
             * Sets the value of the f15B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF15B(String value) {
                this.f15B = value;
            }

            /**
             * Gets the value of the f30T property.
             * 
             */
            public int getF30T() {
                return f30T;
            }

            /**
             * Sets the value of the f30T property.
             * 
             */
            public void setF30T(int value) {
                this.f30T = value;
            }

            /**
             * Gets the value of the f30V property.
             * 
             */
            public int getF30V() {
                return f30V;
            }

            /**
             * Sets the value of the f30V property.
             * 
             */
            public void setF30V(int value) {
                this.f30V = value;
            }

            /**
             * Gets the value of the f36 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF36() {
                return f36;
            }

            /**
             * Sets the value of the f36 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF36(String value) {
                this.f36 = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="F32B" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="F57D" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f32B",
            "f57D"
        })
        public static class SeqB1 {

            @XmlElement(name = "F32B", required = true)
            protected String f32B;
            @XmlElement(name = "F57D", required = true)
            protected String f57D;

            /**
             * Gets the value of the f32B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF32B() {
                return f32B;
            }

            /**
             * Sets the value of the f32B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF32B(String value) {
                this.f32B = value;
            }

            /**
             * Gets the value of the f57D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF57D() {
                return f57D;
            }

            /**
             * Sets the value of the f57D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF57D(String value) {
                this.f57D = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="F33B" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="F53A" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="F57D" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f33B",
            "f53A",
            "f57D"
        })
        public static class SeqB2 {

            @XmlElement(name = "F33B", required = true)
            protected String f33B;
            @XmlElement(name = "F53A", required = true)
            protected String f53A;
            @XmlElement(name = "F57D", required = true)
            protected String f57D;

            /**
             * Gets the value of the f33B property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF33B() {
                return f33B;
            }

            /**
             * Sets the value of the f33B property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF33B(String value) {
                this.f33B = value;
            }

            /**
             * Gets the value of the f53A property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF53A() {
                return f53A;
            }

            /**
             * Sets the value of the f53A property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF53A(String value) {
                this.f53A = value;
            }

            /**
             * Gets the value of the f57D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF57D() {
                return f57D;
            }

            /**
             * Sets the value of the f57D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF57D(String value) {
                this.f57D = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="F15C" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="F24D" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f15C",
            "f24D"
        })
        public static class SeqC {

            @XmlElement(name = "F15C", required = true)
            protected String f15C;
            @XmlElement(name = "F24D", required = true)
            protected String f24D;

            /**
             * Gets the value of the f15C property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF15C() {
                return f15C;
            }

            /**
             * Sets the value of the f15C property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF15C(String value) {
                this.f15C = value;
            }

            /**
             * Gets the value of the f24D property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF24D() {
                return f24D;
            }

            /**
             * Sets the value of the f24D property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF24D(String value) {
                this.f24D = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="F15E" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="RFGroup_1">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RFBlock">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="F22L" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                             &lt;element name="UTI" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "f15E",
            "rfGroup1"
        })
        public static class SeqE {

            @XmlElement(name = "F15E", required = true)
            protected String f15E;
            @XmlElement(name = "RFGroup_1", required = true)
            protected MXmlDetailsS.Sndr.SeqE.RFGroup1 rfGroup1;

            /**
             * Gets the value of the f15E property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getF15E() {
                return f15E;
            }

            /**
             * Sets the value of the f15E property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setF15E(String value) {
                this.f15E = value;
            }

            /**
             * Gets the value of the rfGroup1 property.
             * 
             * @return
             *     possible object is
             *     {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 }
             *     
             */
            public MXmlDetailsS.Sndr.SeqE.RFGroup1 getRFGroup1() {
                return rfGroup1;
            }

            /**
             * Sets the value of the rfGroup1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 }
             *     
             */
            public void setRFGroup1(MXmlDetailsS.Sndr.SeqE.RFGroup1 value) {
                this.rfGroup1 = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RFBlock">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="F22L" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                   &lt;element name="UTI" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rfBlock"
            })
            public static class RFGroup1 {

                @XmlElement(name = "RFBlock", required = true)
                protected MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock rfBlock;

                /**
                 * Gets the value of the rfBlock property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock }
                 *     
                 */
                public MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock getRFBlock() {
                    return rfBlock;
                }

                /**
                 * Sets the value of the rfBlock property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock }
                 *     
                 */
                public void setRFBlock(MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock value) {
                    this.rfBlock = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="F22L" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *         &lt;element name="UTI" type="{http://www.w3.org/2001/XMLSchema}string"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "f22L",
                    "uti"
                })
                public static class RFBlock {

                    @XmlElement(name = "F22L", required = true)
                    protected String f22L;
                    @XmlElement(name = "UTI", required = true)
                    protected String uti;

                    /**
                     * Gets the value of the f22L property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getF22L() {
                        return f22L;
                    }

                    /**
                     * Sets the value of the f22L property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setF22L(String value) {
                        this.f22L = value;
                    }

                    /**
                     * Gets the value of the uti property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUTI() {
                        return uti;
                    }

                    /**
                     * Sets the value of the uti property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUTI(String value) {
                        this.uti = value;
                    }

                }

            }

        }

    }

}
