//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.02.20 at 09:58:37 AM CET 
//


package tmp;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the tmp package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: tmp
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MXmlDetailsS }
     * 
     */
    public MXmlDetailsS createMXmlDetailsS() {
        return new MXmlDetailsS();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr }
     * 
     */
    public MXmlDetailsS.Sndr createMXmlDetailsSSndr() {
        return new MXmlDetailsS.Sndr();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqE }
     * 
     */
    public MXmlDetailsS.Sndr.SeqE createMXmlDetailsSSndrSeqE() {
        return new MXmlDetailsS.Sndr.SeqE();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 }
     * 
     */
    public MXmlDetailsS.Sndr.SeqE.RFGroup1 createMXmlDetailsSSndrSeqERFGroup1() {
        return new MXmlDetailsS.Sndr.SeqE.RFGroup1();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.GeneralInfo }
     * 
     */
    public MXmlDetailsS.GeneralInfo createMXmlDetailsSGeneralInfo() {
        return new MXmlDetailsS.GeneralInfo();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqA }
     * 
     */
    public MXmlDetailsS.Sndr.SeqA createMXmlDetailsSSndrSeqA() {
        return new MXmlDetailsS.Sndr.SeqA();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqB }
     * 
     */
    public MXmlDetailsS.Sndr.SeqB createMXmlDetailsSSndrSeqB() {
        return new MXmlDetailsS.Sndr.SeqB();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqB1 }
     * 
     */
    public MXmlDetailsS.Sndr.SeqB1 createMXmlDetailsSSndrSeqB1() {
        return new MXmlDetailsS.Sndr.SeqB1();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqB2 }
     * 
     */
    public MXmlDetailsS.Sndr.SeqB2 createMXmlDetailsSSndrSeqB2() {
        return new MXmlDetailsS.Sndr.SeqB2();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqC }
     * 
     */
    public MXmlDetailsS.Sndr.SeqC createMXmlDetailsSSndrSeqC() {
        return new MXmlDetailsS.Sndr.SeqC();
    }

    /**
     * Create an instance of {@link MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock }
     * 
     */
    public MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock createMXmlDetailsSSndrSeqERFGroup1RFBlock() {
        return new MXmlDetailsS.Sndr.SeqE.RFGroup1 .RFBlock();
    }

}
